### PR TITLE
CreateStandardColorMap Refactor

### PR DESCRIPTION
**Pull request by RubioJr9**
Changes:
- Fixed value scaling for alpha values in ColorMap
CreateStandardColorMap changes:
- Set UI size to fixed and changed custom color map buttons
- Fixed value range for color map preview so the selection range is always in [0,1]
- Preview points can be reselected and dragged
- Preview points can be deleted with middle mouse button too, so it can be cancelled when you haven't dropped a point yet
- Preview points are clamped to the nearest neighbors, which solves the problem of having multiple points at the same x value

### CODE REVIEW

**Comment by dcwhite** [comment]
Issues to test this with:
- [ ] #2006 
- [ ] #1349 
- [ ] #1127

**Comment by RubioJr9** [comment]
> Issues to test this with:
> 
>     * [ ]  [Adjust alpha hues in createstandardcolormap, part 3 #2006](https://github.com/SCIInstitute/SCIRun/issues/2006)
> 
>     * [ ]  [CreateStandardColorMap improvements, part 2: improve performance of GUI #1349](https://github.com/SCIInstitute/SCIRun/issues/1349)
> 
>     * [ ]  [SCIRun crashes when changing the colormaps #1127](https://github.com/SCIInstitute/SCIRun/issues/1127)

Thanks for linking those. We should be able to close #2006 with this. I'll test performance on my old macbook to see if it's still necessary. I didn't get any crashes on linux, so I'll test Mac

**Review by jessdtate — APPROVED** [review]

**Review by dcwhite — CHANGES_REQUESTED** [review]
Screen Shot 2021-12-10 at 2 24 57 PM
Screen Shot 2021-12-10 at 2 22 49 PM

Layout of the UI needs some fixing on Mac (and likely elsewhere)

**Comment by dcwhite** [comment]
Top is PR, bottom is original.

**Review by dcwhite — APPROVED** [review]

**Pull request merged**
