### PR TITLE
Matlab strings--potential fix for scipy read error

### PR DESCRIPTION
**Pull request by dcwhite**
@jessdtate can you verify this fixes the scipy error referenced in #1692? Also check round-trip save/load for basically every other matlab file type and program that reads/writes such types...

### CODE REVIEW

**Comment by jessdtate** [comment]
There seems to be a problem reading integer matrices into scirun now.  Before, they could be read from matlab.  Here is the error from a saved matrix (same from Python and matlab):

Message: Import failed. 
ERROR: /Users/jess/software/SCIRun/src/Modules/DataIO/GenericReader.h(190): Throw in function virtual void SCIRun::Modules::DataIO::GenericReader >, SCIRun::Modules::MatrixPortTag>::execute() [HType = boost::shared_ptr >, PortTag = SCIRun::Modules::MatrixPortTag] Dynamic exception type: boost::exception_detail::clone_impl std::exception::what: Import failed. [SCIRun::Core::tag_error_message*] = Import failed. 

[Matlab_save_int_matrix.mat.zip](https://github.com/SCIInstitute/SCIRun/files/1432242/Matlab_save_int_matrix.mat.zip)
[python_save_int_matrix.mat.zip](https://github.com/SCIInstitute/SCIRun/files/1432243/python_save_int_matrix.mat.zip)

**Comment by jessdtate** [comment]
looks like that ints on matrix doesn't work with ports at all.

**Comment by dcwhite** [comment]
OK I'll take a look

**Comment by jessdtate** [comment]
a slight correction,  ints from matlab didn't work either, but the error was just: import failed.

**Comment by jessdtate** [comment]
I can get it to work with any fields.  I still get the error: TypeError: Expecting miINT8 as data type

**Comment by dcwhite** [comment]
OK I'll close this and come up with a different fix.

**Comment by jessdtate** [comment]
Maybe we should merge this into master?   It works with matrix files, so it's half fix at least.  I've been including it in local builds for a while to deal with matrix files.

**Comment by dcwhite** [comment]
I can see if I can merge it in with a feature flag--enabled at run-time, or a setting which you can save as turned on.

**Review by jessdtate — APPROVED** [review]

**Pull request closed without merging**
