### PR TITLE
Viewscene adjustments

### PR DESCRIPTION
**Pull request by cbrightsci**

### CODE REVIEW

**Comment by dcwhite** [comment]
@cbrightsci An old glitch reemerged: when you add a ViewScene (on Mac atleast), the config window pops up very quickly before being hidden. It should start hidden.

**Comment by dcwhite** [comment]
@cbrightsci I connected one CLV->SF to a ViewScene. Opened new object picker, deselected the checkbox for ShowField:0, and then two unchecked boxes appeared:
screenshot 2015-07-08 15 48 46

**Comment by dcwhite** [comment]
Looks like that just happens with one connected. With two SFs, the checkboxes behave correctly.

**Comment by cbrightsci** [comment]
@dcwhite It should be good now.

**Comment by dcwhite** [comment]
Second issue is fixed. Still seeing the first issue.

Suggestions:
- [ ] Move "Objects" tab to first position in Configure screen so it show up first. 
- [ ] Then add hotkey to ViewScene to bring up the list. It's heavily used so we need quick access.

**Comment by dcwhite** [comment]
Cool I will test early tomorrow.

**Pull request merged**
