### PR TITLE
Selection issue

### PR DESCRIPTION
**Pull request by Haydelj**
I added a button that enables a hack to fix the selection problem related to rendering the selection buffer on certain apple hardware/software configurations. A bandaid fix for issue #1996

### CODE REVIEW

**Comment by jessdtate** [comment]
Yeah, the option needs to move to preferences, if possible.

**Comment by dcwhite** [comment]
@Haydelj Todo:
- [ ] Change button to checkbox
- [ ] Fix merge

I will take care of the move to preferences.

**Comment by dcwhite** [comment]
@Haydelj Needs a merge fix

**Comment by Haydelj** [comment]
done

**Comment by dcwhite** [comment]
I'll merge this one today

**Pull request merged**
