### PR TITLE
Large mesh performance

### PR DESCRIPTION
**Pull request by Haydelj**
Fixes some of the logic for generating meshes is showField as well as fixes the errors is spire's VarBuffer class. This now allows us to process models with VBO's up to 4GiB. Further Improvements are awaiting regression testing for the renderer

### CODE REVIEW

**Comment by Haydelj** [comment]
> @Haydelj This is a perfect example of code in need of unit testing. Now that src/Externals/spire code can be just included normally, it should be easy to write a VarBuffer test. And although it will take a bit of refactoring to extract the changed code from ShowField, a unit test for buffer size calculation should not be too hard either (Extract a class with a couple methods, to test just that computation without depending on modules or field objects). Please add these before this gets merged. Think of it as a preview of the requirements for the massive ShowField refactoring project.

@dcwhite testing the calculations for buffer size should be easy, we just need to compare the initial size to the utilized size and make sure they are the same. Did you have something in mind for testing varBuffer? It seems that showField running on large meshes (meshes > 4GiB) without crashing is a pretty solid test case for varBuffer and one that It wasn't passing before this pull request at that. Also, do we have a testing framework in place or do we need to create one?

**Comment by dcwhite** [comment]
@Haydelj Yes, we have Google test and ctest. Tests can be added to https://github.com/SCIInstitute/SCIRun/blob/master/src/Interface/Modules/Render/Tests/CMakeLists.txt

**Comment by dcwhite** [comment]
You can copy/paste https://github.com/SCIInstitute/SCIRun/blob/master/src/Interface/Modules/Render/Tests/SRInterfaceTests.cc and use that structure. Anything in the spire directory should be includable, so test away.

**Comment by dcwhite** [comment]
Looked at testing the new buffer size computation, it will require moving lots of code around. Future issues will be forthcoming.

**Comment by dcwhite** [comment]
@jessdtate This one is ready for your review.

**Comment by jessdtate** [comment]
I'm still getting a crash with latvol of size 256^3.  It looks like a nicer crash at least,  an abort instead of a SegFault.  If I'm the only one who is seeing this, we can merge it with a new issue.

**Comment by jessdtate** [comment]
crash report:
System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff9c9d8d42 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff9cac6457 pthread_kill + 90
2   libsystem_c.dylib             	0x00007fff9c93e420 abort + 129
3   GLEngine                      	0x000000011c2a02a7 allocateWCMemory + 233
4   GLEngine                      	0x000000011c2a0758 gleAcquireBufferData + 249
5   GLEngine                      	0x000000011c2a04d3 glBufferData_Exec + 524
6   libInterface_Modules_Render.dylib	0x00000001071e18ed ren::VBOMan::addInMemoryVBO(void*, unsigned long, std::__1::vector<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long, bool>, std::__1::allocator<std::__1::tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned long, bool> > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 77
7   libInterface_Modules_Render.dylib	0x00000001070000f6 SCIRun::Render::SRInterface::handleGeomObject(boost::shared_ptr<SCIRun::Graphics::Datatypes::GeometryObjectSpire>, int) + 2278
8   libInterface_Modules_Render.dylib	0x0000000106fa3e9a SCIRun::Gui::ViewSceneDialog::newGeometryValue(bool) + 2010
9   QtCore                        	0x000000010a6b87cd QObject::event(QEvent*) + 111
10  QtGui                         	0x0000000109af6936 QWidget::event(QEvent*) + 3446
11  QtGui                         	0x0000000109ab5329 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 195
12  QtGui                         	0x0000000109ab66a6 QApplication::notify(QObject*, QEvent*) + 436
13  QtCore                        	0x000000010a6a7d09 QCoreApplication::notifyInternal(QObject*, QEvent*) + 111
14  QtCore                        	0x000000010a6a8734 QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 726
15  com.apple.CoreFoundation      	0x00007fff870c68c1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
16  com.apple.CoreFoundation      	0x00007fff870a77bd __CFRunLoopDoSources0 + 557
17  com.apple.CoreFoundation      	0x00007fff870a6cb6 __CFRunLoopRun + 934
18  com.apple.CoreFoundation      	0x00007fff870a66b4 CFRunLoopRunSpecific + 420
19  com.apple.HIToolbox           	0x00007fff86606ebc RunCurrentEventLoopInMode + 240
20  com.apple.HIToolbox           	0x00007fff86606cf1 ReceiveNextEventCommon + 432
21  com.apple.HIToolbox           	0x00007fff86606b26 _BlockUntilNextEventMatchingListInModeWithFilter + 71
22  com.apple.AppKit              	0x00007fff84b9ba54 _DPSNextEvent + 1120
23  com.apple.AppKit              	0x00007fff853177ee -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2796
24  com.apple.AppKit              	0x00007fff84b903db -[NSApplication run] + 926
25  QtGui                         	0x0000000109a734e3 QEventDispatcherMac::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 493
26  QtCore                        	0x000000010a6a5274 QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 76
27  QtCore                        	0x000000010a6a53d1 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 335
28  QtCore                        	0x000000010a6a819f QCoreApplication::exec() + 199
29  libInterface_Application.dylib	0x0000000106297ca5 SCIRun::Gui::SCIRunGuiRunner::SCIRunGuiRunner(QApplication&) + 437
30  libInterface_Application.dylib	0x000000010626ca45 SCIRun::Gui::GuiApplication::run(int, char const**) + 53
31  SCIRun_test                   	0x0000000106240661 mainImpl(int, char const**, char**) + 513
32  libdyld.dylib                 	0x00007fff9c8aa235 start + 1

**Comment by Haydelj** [comment]
Yeah, I think I mentioned this at our meeting a couple of weeks ago. This only fixes geometry generation so now we can generate vbo's larger than 4GiB without crashing but we still can't render meshes larger than 4GiB. I'll have to do some research to figure out if OpenGL has support for this. Otherwise like I said we can split up vbo's larger than 4GiB into smaller ones.

**Pull request merged**
