### PR TITLE
Edit camera state variables

### PR DESCRIPTION
**Pull request by RubioJr9**
Converted CameraLookAt and CameraRotation to strings so they can be set through the python interface.

Edit 2/10:
Camera Rotation
-the quaternion is now being normalized so it can no longer be given garbage numbers
-using regex 
-wrong formatting sets to default

Camera Distance
-enforce positive, non-zero numbers

### CODE REVIEW

**Comment by dcwhite** [comment]
@RubioJr9 This one has Windows build errors; please fix (I'm excited I get to say this now with very little effort...)

**Comment by RubioJr9** [comment]
Windows build passes!

**Comment by dcwhite** [comment]
@RubioJr9 Can this one get one or more test networks? It would be great to have a color-coordinated latvol, piped to multiple ViewScenes, each with a set view using the new state parameters, and labeled with module notes (or ShowStrings). Then another network that loops through a list of values that control the rotation/position via python code using InterfaceWithPython.

**Comment by dcwhite** [comment]
@jessdtate This one is ready for you

**Comment by dcwhite** [comment]
@jessdtate Reviewed?

**Pull request merged**
