### PR TITLE
Fix ViewScene destructor crash after selecting a widget

### PR DESCRIPTION
**Pull request by dcwhite**
To test, load/create any network with a widget (e.g. src/ExampleNets/Renderer/embb2.srn5), move the widget around (shift-click-drag), then click New Network OR load a new network file OR close the whole program, and SCIRun should not crash (before, it would in any of those cases). Try all three ways to crash it.

ALSO: test with resizing the ViewScene window. Move widget around, then resize the ViewScene viewer window, then resize some more--widget should still be selectable and should not crash.

### CODE REVIEW

**Comment by dcwhite** [comment]
@jessdtate @allywarner @RubioJr9 Urgent testing needed since it's @Haydelj's last day!!!

**Comment by dcwhite** [comment]
Something in this change seems to break widget selection after resizing the VS window. Found by @allywarner. Switching to draft.

**Comment by RubioJr9** [comment]
Sorry, I didn't see this post earlier. I'm building it now

**Comment by dcwhite** [comment]
@allywarner ready to test again! Note updated testing instructions.

**Comment by dcwhite** [comment]
I think Mac is working, but not Windows. Grr.

**Comment by dcwhite** [comment]
Just kidding, tested on Windows and it seems good there too.

**Review by jessdtate — APPROVED** [review]

**Comment by RubioJr9** [comment]
I tested on all 3 platforms. Both the destructor crash and resizing bug are gone.

**Comment by dcwhite** [comment]
Thanks a lot! I'll merge this today

**Pull request merged**
