### PR TITLE
Importing state of v4 nets

### PR DESCRIPTION
**Pull request by Nahusa**
TODO
Add modules ViewScene
Issue : https://github.com/SCIInstitute/SCIRun/issues/1219
Changes : Mapping logic moved to an xml config
Reviewers : @dcwhite @jessdtate

### CODE REVIEW

**Comment by dcwhite** [comment]
Thanks! I'm building this on Windows now, we ought to be able to merge later today.

**Comment by dcwhite** [comment]
@Nahusa  Please merge SCIInstitute/master to get a Travis build script improvement. Also, the Windows build is broken on Visual Studio 2013 (later compilers are probably OK), so I'll need to push some changes after I test this on Mac (probably tomorrow).

**Comment by Nahusa** [comment]
@dcwhite Merged SCIInstitute/master.

**Comment by dcwhite** [comment]
Finally got VS2017 working, so I can check this now

**Pull request merged**
