### PR TITLE
Environment bundle

### PR DESCRIPTION
**Pull request by jessdtate**
This is a branch for two modules: InsertEnvironmentIntoBundle and GetStringsFromBundle.  GetStringsFromBundle is completely ported and is working properly.  InsertEnvironmentIntoBundle is not working yet.  The guts of the module have been commented out because it is dependent on environment.cc which has not been converted.  This is a bit complicated for me to convert.

### CODE REVIEW

**Comment by dcwhite** [comment]
@jessdtate Before I checkout this one, can you merge upstream/master into it (which will contain your first PR)? That will "slim down" the commit history and diff.

**Comment by jessdtate** [comment]
I thought I had already done that.  done now.

**Comment by dcwhite** [comment]
Thanks

**Comment by dcwhite** [comment]
Try merging this branch into your PR branch. It works on Windows and I'm building on Mac to test it there too. https://github.com/SCIInstitute/SCIRun/commits/environmentFinish

**Comment by dcwhite** [comment]
Works on Mac too: https://www.dropbox.com/s/xtfue0oz2h8qo8p/Screenshot%202015-10-29%2017.08.17.png?dl=0

**Comment by jessdtate** [comment]
I'm getting some build errors.  I will see if I can work them out.

**Comment by jessdtate** [comment]
I got it to build, but it doesn't import the environment variables from the session (outside of SCIRun)

**Comment by dcwhite** [comment]
To get external env, you can re-merge the same branch as above, or copy over this commit: https://github.com/SCIInstitute/SCIRun/commit/c2b27a7eb746468de0741756a8253f32f2d9b678

**Comment by jessdtate** [comment]
Looks like it is working.  I am able to pass filenames and read them into scirun, so goal achieve.  Though it seems to require the variable to be capitalized, which is reasonable, but needs to documentation.  I can update the wiki before I forget.

**Comment by jessdtate** [comment]
actually the lower case is working now.

**Pull request merged**
