### PR TITLE
AutoReadFile module

### PR DESCRIPTION
**Pull request by dcwhite**
New module with smarter, simpler file reading functionality. Can read most matrix and field input types.

### CODE REVIEW

**Comment by dcwhite** [comment]
Will also close #289, for beaucoup XP

**Comment by dcwhite** [comment]
@wgood This new module will read `.mat` files first as Matlab, then as SCIRun, with no need to specify the file type--just connect a field or matrix pipe and it will read it automatically. So it ought to close #2083 as well.

**Comment by wgood** [comment]
Awesome, thanks so much @dcwhite!

**Comment by dcwhite** [comment]
@jessdtate This is ready, with the older Qt used in the action build for you to install and try.

**Comment by dcwhite** [comment]
@Sailanarmo Some template code for you to peruse

**Comment by dcwhite** [comment]
@jessdtate Did the older Qt fix work?

**Comment by dcwhite** [comment]
Thanks. The goal was "minimum user interaction" in the spirit of "advanced SCIRun module," but yeah, we'll see how users like it

**Pull request merged**
