### PR TITLE
Scalar Centering

### PR DESCRIPTION
**Pull request by RubioJr9**
-Fixed scalar centering
-Made enum for datatypes on vectors and tensors

Issues:
#2007

### CODE REVIEW

**Comment by RubioJr9** [comment]
> data located on the faces or edges are not showing

For scalars? I thought they only used node and cell data

**Comment by dcwhite** [comment]
@jessdtate We need more network examples posted here for testing

**Comment by RubioJr9** [comment]
Faces and edges should work now but I couldn't figure out how to get those datatypes from a lat vol

**Comment by jessdtate** [comment]
[scalar_glyph_test.srn5.zip](https://github.com/SCIInstitute/SCIRun/files/3833075/scalar_glyph_test.srn5.zip)

**Pull request merged**
