### PR TITLE
Showfieldglyphs

### PR DESCRIPTION
**Pull request by cbrightsci**

### CODE REVIEW

**Comment by dcwhite** [comment]
:yum:

**Comment by dcwhite** [comment]
@cbrightsci Due to the stylesheet (and there's an outstanding issue for this) it's impossible to see which glyph types are enabled/available. Can you change this widget to a combobox, and only include ones that are available now?
glyphchoices

**Comment by dcwhite** [comment]
@cbrightsci @aylakhan Here's a comparison using default settings, for cell-centered vectors. 

v5 arrows are too thin--nearly invisible. Also, no actual arrowheads are visible here.
viewscene_2015 05 20 141232 836_3

v5 lines are better.
viewscene_2015 05 20 141046 158_2

here is v4
torsovectors

**Comment by cbrightsci** [comment]
@dcwhite does adjusting the scale help?

**Comment by cbrightsci** [comment]
@dcwhite What network is this?

**Comment by dcwhite** [comment]
Scaling of the arrows didn't do much this zoomed out. Take src/ExampleNets/regression/streamlinesTorso.srn5 and add a SFG to the CalculateGradients module on the left.

**Comment by dcwhite** [comment]
To get v4 output, try this network (adjusting path to SCIRun data dir): https://www.dropbox.com/s/u1udmb0vjo49ens/torsoVectors.srn?dl=0

**Comment by cbrightsci** [comment]
Here it is with 50 scale.
viewscene_2015 05 20 144318 739_1

**Comment by aylakhan** [comment]
Is that scale consistent with scaling in SCIRun 4?

**Comment by dcwhite** [comment]
OK I didn't go up that high. Yeah check to see how the scales match up.

**Comment by cbrightsci** [comment]
my version4 is giving me problems. I'm rebuilding it :(

**Comment by cbrightsci** [comment]
@dcwhite how about crossing out this disabled ones?
image

**Comment by dcwhite** [comment]
Not the best but just do that for this release since it's quicker.

**Comment by cbrightsci** [comment]
Done

**Pull request merged**
