### PR TITLE
Tensor fixes: color mapping, normalizing before scaling, render thresholds, tensor lines, tensor scalars, & bug fixes

### PR DESCRIPTION
**Pull request by RubioJr9**
Changes:
-Fixed tensor color mapping(updated scirun pages). 
-Added checkbox for normalize before scaling.
-Added checkbox and value amount for not rendering below threshold.
-Tensors with 2 eigen values of 0 rendered as line.
-Tensors with 3 eigen values of 0 rendered as point.
-Tensors with negative eigen values are no longer set to spheres and now colored. 
Fixes of SCIRun 4 implementations: 
-Disabled the scaling value from affecting threshold. 
-Stopped eigen values below the threshold being set to the threshold. 
-Threshold now checked against magnitude of all eigenvalues instead of each eigen value. 
-Fixed bug where tensors are rendered as lines or points if eigen values are below threshold, even if the checkbox is not enabled.

Reviewers:
@jessdtate @dcwhite

### CODE REVIEW

**Comment by jessdtate** [comment]
I get some crashes with I rotate the scene

**Comment by jessdtate** [comment]
DTI dataset?

**Comment by RubioJr9** [comment]
Jess, can you show me on Monday how you got this issue? I can't replicate it. I even tried recloning it and compiling. Note: I merged the newest changes on master into this branch.

**Comment by RubioJr9** [comment]
fixed transparency issue

**Comment by dcwhite** [comment]
I will test this on windows today

**Pull request merged**
