### PR TITLE
Update with redirected pages made in scirun.pages

### LINKED ISSUE #2326: host both RTD and github pages
Here is a link to a total copy:
https://stackoverflow.com/questions/62683329/how-to-self-host-read-the-docs-using-github-pages

our solution could just be a redirect of github pages to RTD

### PR DESCRIPTION
**Pull request by nids2001**
Redirects old gh pages to new RTD docs site
Closes #2326

### CODE REVIEW

**Comment by dcwhite** [comment]
This looks like you deleted way too much...what was the intent?

**Comment by dcwhite** [comment]
Oh it's from the gh-pages branch that is WAY out of date. I was looking at the wrong diff...

**Comment by nids2001** [comment]
Yeah there were a lot of files in the old branch. Was there a better way to do this?

**Comment by dcwhite** [comment]
http://sciinstitute.github.io/SCIRun/ is built from `master/docs` folder. The gh-pages site...not sure if that's still hosted anywhere. Let me investigate

**Pull request closed without merging**
