### PR TITLE
Draw Order Fix

### PR DESCRIPTION
**Pull request by Haydelj**
I used a bounding sphere around the scene bounding box to generate near and far clipping planes in order to reduce Z-Fighting. Right now the bounding sphere generation is tied to auto view. Before auto view is pressed we use the default behavior with the near clipping plane set to 1.0. I also fixed SRInterface so that it actually passes the projection matrix from SRCamera to spire.

### CODE REVIEW

**Comment by dcwhite** [comment]
@Haydelj Is this tied to a specific issue #? If so please indicate. Also, it would be nice if you provided some example "before/after" screenshots attached here. Thanks.

**Comment by jessdtate** [comment]
This was reported in Sumientra's issue #1846.

**Comment by jessdtate** [comment]
also #952

**Comment by Haydelj** [comment]
Now also fixes auto view scene for glyphs resolving issue #1463

**Comment by dcwhite** [comment]
This one will be after #1896

**Comment by dcwhite** [comment]
@Haydelj TODO: add toString(), move font files back

**Comment by jessdtate** [comment]
@Haydelj found some bugs with the math he was using for this fix.  Stay tuned for an update

**Comment by Haydelj** [comment]
Before:
Screen Shot 2019-04-04 at 12 38 47 PM
Screen Shot 2019-04-04 at 12 40 04 PM

After:
Screen Shot 2019-04-04 at 12 46 01 PM
Screen Shot 2019-04-04 at 12 47 17 PM

**Pull request merged**
