### PR TITLE
Save background color

### PR DESCRIPTION
**Pull request by cbrightsci**
This is for saving the background color in networks.

### CODE REVIEW

**Comment by dcwhite** [comment]
@cbrightsci Looks good, just include a sample network. Save out multiple viewscenes with different backgrounds and commit that in src/ExampleNets/regression.

**Comment by cbrightsci** [comment]
@dcwhite A sample network has been added.

**Comment by cbrightsci** [comment]
@dcwhite I've also merged master into the branch.

**Comment by dcwhite** [comment]
Thanks, I'll wait for Travis to finish, test the network, then merge if all green.

**Pull request merged**
