### PR TITLE
Auto rotate

### PR DESCRIPTION
**Pull request by Haydelj**
Adds auto rotate controls and @jessdtate's favorite feature resolving issues #1705 and #717.

### CODE REVIEW

**Comment by dcwhite** [comment]
The rotate buttons work fine, but I can't get the drag-spin function to work (Windows). I'll try on Mac.

**Comment by dcwhite** [comment]
Yes, the drag-spin works on Mac/Qt4. I'm going to try Qt5 on Mac to see if that's the difference (Windows was 5)

**Comment by dcwhite** [comment]
@Haydelj It does work, mostly, on Mac/Qt5. I had to give the trackpad a little more velocity to get it to spin though. I tried faster dragging on Windows and it definitely doesn't work. Any ideas? Or will you have to debug it?

**Comment by jessdtate** [comment]
I get some major slow downs when trying to manually rotate with this branch

**Comment by jessdtate** [comment]
The mouse autorotate control should probably be in preferences, rather than in the view scene settings.  This can be a new issue if preferred.

**Comment by jessdtate** [comment]
I'm getting a bit of z-fighting.  Not too bad, but it is visible with some angles.

**Comment by jessdtate** [comment]
This is a video of the z fighting
[autorotate.mov.zip](https://github.com/SCIInstitute/SCIRun/files/3332324/autorotate.mov.zip)

**Pull request merged**
