### PR TITLE
Various

### PR DESCRIPTION
**Pull request by dcwhite**

### CODE REVIEW

**Comment by dcwhite** [comment]
Ahhhh, too many builds. I'll need to split up the action build file, one for push and one for pull_request.

**Comment by dcwhite** [comment]
@jessdtate @allywarner Needs review. And yes, please point out the crappy description so I can improve it.

**Comment by dcwhite** [comment]
I'm going to add one more commit here for @nids2001. Please wait to review until that's in

**Comment by allywarner** [comment]
It would be nice to be able to filter based on UI and then use the "Starts with" within that filter.

**Comment by dcwhite** [comment]
> It would be nice to be able to filter based on UI and then use the "Starts with" within that filter.

I was a bit lazy and added it as another option in the dropdown, so they can't be combined yet. What's the use case, just to reduce the result list? Mainly I added this option for developer testing of all UIs.

**Comment by allywarner** [comment]
Yeah! It's always nice to be able to filter within a filter, but I can't see a lot of users needing that.

**Pull request merged**
