### PR TITLE
Tikhonov Module tests

### PR DESCRIPTION
**Pull request by jcollfont**
Added some tests for the Tikhonov module.

So far these are forward matrix and data vector tests and include:

NULL forward matrix + NULL data vector 
NULL forward matrix + random data vector (3x1)
ID forward matrix (3x3)+ NULL data vector
ID forward matrix (3x3)+ RAND data vector (3x1)
ID forward matrix (4x3)+ RAND data vector (3x1)  - should work and fails
ID forward matrix (3x4)+ RAND data vector (4x1)  - should work and fails
ID forward matrix (3x4)+ RAND data vector (3x1) - should fail and works
ID forward matrix (3x3)+ RAND data vector (3x1)

### CODE REVIEW

**Comment by dcwhite** [comment]
@jcollfont Please merge this branch with the latest master, then push your branch again. It's quite out of date.

**Comment by jcollfont** [comment]
@dcwhite Second time around is automatic, right?

**Comment by dcwhite** [comment]
Yes, pushed commits to your PR branch show up automatically once the PR is made.

**Comment by dcwhite** [comment]
@jcollfont This is a good start. Could you add more comments to the code file, indicating which test cases are working properly? That would make it easier to find the faulty ones and fix them.

**Comment by dcwhite** [comment]
So for example, you could add an all caps comment, explaining each issue:
```
// TODO: this case does not throw an exception, but should since matrix sizes are ... and thus ...
```

**Comment by dcwhite** [comment]
Perfect, thanks. I'll be able to start investigating the failures next week.

**Pull request merged**
