### PR TITLE
fixed light ui

### LINKED ISSUE #1474: viewscene: get lights to move correctly from GUI input
The lights controlled from the lights tab in the config menu of the viewscene need to be fixed so the movement occurs with the movement of the dot.

### PR DESCRIPTION
**Pull request by Haydelj**
Closes #1474

### CODE REVIEW

**Comment by allywarner** [comment]
From a user point of view, what are the slider bars supposed to do? Say somebody has never used SCIRun, where would they find out what these bars are actually controlling? The buttons to choose color are also named "PushButton." I think a more meaningful name would be appropriate so that users would know what they were for too. Something simple like "Choose Light Color."

**Comment by Haydelj** [comment]
I added tooltips to the sliders labeling them Azimuth and Inclination and I fixed the button labels

**Comment by allywarner** [comment]
At the bottom of the UI, there's "Click on circle to change light color/brightness." Since you've removed the circle, I would change this instruction, and probably put it at the top so the user can see it first. Also the tool tips are great, but maybe a very short explanation of what those terms mean would be helpful.

**Comment by dcwhite** [comment]
Consider a table widget to add widget context but reduce duplication:
https://doc.qt.io/qt-5/qtablewidget.html

It's possible to add sliders and checkboxes and push buttons in each cell. This will make it easy to enable more than 4 lights later on.

image

**Comment by dcwhite** [comment]
@Haydelj A new merge conflict to fix.

The GUI is acceptable now, we can overhaul all those tabs with nicer tables and stuff later.

**Comment by allywarner** [comment]
When you update the UI again, I would add some instruction to the tool tips. "Higher does this" and "lower does this" for the Azimuth and the Inclination.

**Pull request merged**
