### PR TITLE
Goodbye Cleaver 1

### PR DESCRIPTION
**Pull request by dcwhite**

### CODE REVIEW

**Comment by jessdtate** [comment]
Hmm.  Github changed the layout and now I cannot find the builds that it generates.

**Comment by jessdtate** [comment]
Maybe it's just not here:
`Warning: No files were found with the provided path: bin/SCIRun/SCIRun-5.0.beta.*-Darwin.pkg. No artifacts will be uploaded.`

**Comment by dcwhite** [comment]
Looks like the master-deployment part of the script pushes an intermediate tag that messes up the package name, so it doesn't match and doesn't get copied. I'll need another PR to fix that.

**Comment by dcwhite** [comment]
Or maybe I can just push it here...let me try

**Comment by dcwhite** [comment]
@jessdtate Downloadable installer is working again

**Review by jessdtate — APPROVED** [review]

**Pull request merged**
