### PR TITLE
CalculateNodeNormals module conversion

### PR DESCRIPTION
**Pull request by nids2001**
Convert CalculateNodeNormals module. Renamed to GenerateNodeNormals to better describe module behavior.

### CODE REVIEW

**Comment by jessdtate** [comment]
The behavior is as I expect and matches SR4

**Comment by jessdtate** [comment]
[generateNodeNormals.srn5.zip](https://github.com/SCIInstitute/SCIRun/files/5845666/generateNodeNormals.srn5.zip)

**Comment by dcwhite** [comment]
@jessdtate Thanks. @nids2001 since there are a couple steps to getting this test network working in the regression suite, I'll take care of it this time.

**Review by dcwhite — APPROVED** [review]

**Comment by jessdtate** [comment]
network with latvol
[generateNodeNormals.srn5.zip](https://github.com/SCIInstitute/SCIRun/files/5858614/generateNodeNormals.srn5.zip)

**Review by dcwhite — APPROVED** [review]

**Review by jessdtate — APPROVED** [review]

**Pull request merged**
