### PR TITLE
Implement module ShowString

### PR DESCRIPTION
**Pull request by dcwhite**
Improved UI compared to 4. Possibly some stability issues on the rendering side; more extensive testing is required.

### CODE REVIEW

**Comment by dcwhite** [comment]
@jessdtate Test this today?

**Comment by jessdtate** [comment]
there was a problem with the default font that was causing some other problems.  Other than that, it was working fine.

**Comment by dcwhite** [comment]
The auto-execute widgets were still a problem, so I'll just remove that feature from those widgets for now.

**Comment by dcwhite** [comment]
@jessdtate Please test again.

**Comment by jessdtate** [comment]
The font is working now, and I can change all the options.  Changing the coordinates does not seem to move the text.  Maybe it is not hooked up?

**Comment by dcwhite** [comment]
Oops, got a bit excited with the double-slashes there. Coordinates should work now.

**Comment by jessdtate** [comment]
everything seems to work now.

**Pull request merged**
