### PR TITLE
Apply FEM voltage source

### PR DESCRIPTION
**Pull request by cbrightsci**

### CODE REVIEW

**Comment by dcwhite** [comment]
Looks good, I think I'm missing an input file though: Matrices/sparseSquare.mat

**Comment by cbrightsci** [comment]
I just tried submitting it to SCIRunTestData, but I don't have permission to push my changes to the repository. @dcwhite

**Comment by dcwhite** [comment]
Try now!

**Comment by cbrightsci** [comment]
The matrix is pretty big (59 MB). I'll see if I can get a smaller one to replace it. It should be there for now though.

**Comment by dcwhite** [comment]
Ugh, OK. That is a bit too big in general. Try to swap it soon.

**Comment by cbrightsci** [comment]
My feelings exactly. I didn't consider the size until I pressed sync. I'll get it switched.

**Pull request merged**
