### PR TITLE
Widget testing and refactoring, SRInterface refactoring, transform testing

### LINKED ISSUE #2056: Refactor SRInterface (part 3) and Widget library
White board pic coming soon

### PR DESCRIPTION
**Pull request by dcwhite**
Closes #2056 

Also updates the stale github workflow parameters.

### CODE REVIEW

**Comment by dcwhite** [comment]
To test: any module that creates widgets. Test all mouse interaction in ViewScene (translate, rotate, scale).
- [ ] GenerateSinglePointProbe
- [ ] GeneratePointSample
- [ ] ShowAndEditDipoles
- [ ] EditMeshBoundingBox

**Comment by dcwhite** [comment]
@allywarner I added a checklist of what to test above.

**Comment by RubioJr9** [comment]
I went through the checklist and I don't have any issues. I like the glyph builder abstraction. What are your thoughts on removing the SphereWidget, DiskWidget, etc. classes and have the create functions in WidgetFactory create a plain widget with the name and position that's given since that's all that is needed of the <Shape>Widget classes?

**Comment by dcwhite** [comment]
That might lose some of the type structure that will come in handy when we get into defining the more complex interactions. It's true those two are mostly the same, but it's not a big deal to keep them around, for now.

**Comment by dcwhite** [comment]
I'll merge this today, but AFTER I make the official X tag (which will happen around 1:30pm).

**Comment by Haydelj** [comment]
@dcwhite @RubioJr9 if you just click on the bounding box (not click and drag) with shift held you can get into a state where it shows red as though it's selected but nothing is selected

**Comment by RubioJr9** [comment]
> @dcwhite @RubioJr9 if you just click on the bounding box (not click and drag) with shift held you can get into a state where it shows red as though it's selected but nothing is selected

I'm seeing this as well with point samples and bbox. It does not happen with the arrowWidget.

**Comment by dcwhite** [comment]
I was seeing something like this too, but wasn't sure what could've caused it. I guess I merged this too soon, but we should be able to figure that out pretty fast.

**Pull request merged**
