### PR TITLE
Memory Duplication Fix

### PR DESCRIPTION
**Pull request by Haydelj**
Makes the transparency rendering system handle it's own sorted IBO's. Though this system does not have any garbage collection it allows us to enable garbage collection for everything else reducing memory usage dramatically. This addresses issue #1083 

Note: When we get a chance we should either completely rework the transparent object rendering system or implement some sort of garbage collection system for the sorted IBO's

### CODE REVIEW

**Comment by dcwhite** [comment]
@Haydelj now this one needs a manual merge by you.

**Comment by dcwhite** [comment]
Looks to be pretty easy though, just one extra field in Core.h

**Comment by dcwhite** [comment]
I'll test this some more--Windows might be behaving better than Mac with the first GC fix.

**Comment by jessdtate** [comment]
GC fix in master still crashes on OS X.  The performance seems the same with new fix, but doesn't crash.

**Pull request merged**
