### PR TITLE
Qt5 problems, and their fixes

### PR DESCRIPTION
**Pull request by dcwhite**
Main quasi-fix: #1982. Still to do: better module placement method.
Also, parts of several other issues, see commit log and links below

### CODE REVIEW

**Comment by RubioJr9** [comment]
I just tested it and I'm still seeing the stacking problem on 10.14.4

**Comment by RubioJr9** [comment]
I just tested it again with the new commit. On the same mac os 10.14.4, when you drag a module, it drops on the right of the screen then snaps into the right position. I wasn't seeing that before. On linux, I got a seg fault the first time I use and execute a typical pattern. When I open it again and try that same pattern, I don't get a seg fault.

**Comment by allywarner** [comment]
If I leave SCIRun for a while (about 5 minutes or so), go to another window, and come back to it the modules are on top of each other again and move when you hover over them.

**Comment by jessdtate** [comment]
> If I leave SCIRun for a while (about 5 minutes or so), go to another window, and come back to it the modules are on top of each other again and move when you hover over them.
> 
> I'm testing on OSX 10.14.6 and Qt 5.13.0.

Not seeing this in 10.15 with qt5.13

**Pull request merged**
