### PR TITLE
module conversion Tutorial update

### PR DESCRIPTION
**Pull request by jessdtate**
This pr contains and update of the module generation documentation, including formatting the common function changes and common errors section.

### CODE REVIEW

**Comment by dcwhite** [comment]
@jessdtate Looks like the grammar fixes done a while ago were lost in a merge. Can this one be redone?

**Comment by dcwhite** [comment]
Or go through https://github.com/SCIInstitute/SCIRun/pull/1456/files and redo all the grammar/spelling fixes.

**Comment by jessdtate** [comment]
OK, I'll fix that.

**Comment by jessdtate** [comment]
I added those corrections.

**Pull request merged**
