### PR TITLE
Closes #1642

### LINKED ISSUE #1642: Interactive Execution with GetSliceFromStructuredFieldByIndices
### Description

Parsing through an image stack with GetSliceFromStructuredFieldByIndices and a showfield is a little tedious right now as I need to right click->execute in the module UI every time I move the slider. I would like the option to have this module execute interactively on release of the mouse when I move the slider around.

### PR DESCRIPTION
**Pull request by dcwhite**
All widgets in GSFSFBI trigger execution now.

### CODE REVIEW

**Comment by dcwhite** [comment]
So turn off spinbox update? Yeah I can add some more checkboxes

**Comment by jessdtate** [comment]
Yeah, It would be nice to have all three options

**Comment by dcwhite** [comment]
OK

**Comment by dcwhite** [comment]
Check out the latest version of this branch to make sure the checkboxes work OK.

**Comment by dcwhite** [comment]
This will also need a fresh review from somebody

**Comment by jessdtate** [comment]
This doesn't quite behave as I would expect.  I think it should be normal interactive with the interactive mode selected without the other checkmarks, ie, execute as it is moved.  then check the execute on release   (which  I think should be default) to enable that option.  Unchecking the interactive mode would mean you have to hit the execute button.  This would mean you don't need the execute on click option for the axes.  

If this is harder to implement, then the interactive mode could be execute on release.

**Comment by dcwhite** [comment]
It was tricky due to there being two widgets for a single state value. I should have removed the global checkbox, to make it less confusing, which I can do now.

**Pull request merged**
